### ISSUE TITLE
Is this project the previous version of the new tree grid view?

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/avl-aml-tools#1]
I tested the project because I was originally assumed it would do...something else (e.g. modification of the standard grid).
Finally I realized, that this project does basically quite the same as the new tree grid views. Is this one the historic precursor for tree grid views? Are there current scenarios where this approach is preferable to the Tree Grid views?

It still works without problems under SP11!

**Comment by EliJDonahue** [comment]
Hi Angela,

I would recommend using the Tree Grid Views in more recent versions of Aras Innovator. It's a supported feature of the platform, so it will be easier to maintain and upgrade as the product evolves.

Eli

**Comment by AngelaIp** [comment]
Hi Eli,
thanks for confirmation! I prefer the TreeGridViews as well. The feature is quite powerful and offers unimagined possibilities. I still only scratch the surface.
 
The ItemType 'Grid' was actually the only ItemType that I've never understood in the past 2 years of working with Aras Innovator. Now that I understand 'Grids', I do not need them anymore. That´s so typical again. ;-)

Angela
